name: NEWSTART API Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Hostel web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          version: 16.x
      - name: Install dependencies
        run: npm install
      - name: build app
        run: yarn build
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: talentPoint.pem # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
      - name: rsync over ssh
        run: rsync -avP dist package.json package-lock.json hostel-admin:~data/hostel-admin
      - name: updating new hostel-admin api version
        run: ssh hostel-admin bash ~data/deploy.sh
